applicationName: "proshop-app-frontend"
replicaCount: 1
image:
  repository: "650251689864.dkr.ecr.us-east-2.amazonaws.com/proshop-app-frontend"
  tag: "latest"
  pullPolicy: IfNotPresent
port: 3000
env:
  backendURL: "https://proshop-backend.99shop.com"
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
ingress:
  create: true
  hostname: proshop-frontend.99shop.com
  tls:
    enabled: true
    secretName: proshop-tls-secret
